site_name: Style Guide For Indenters
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: blue grey

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/indent-logo.png
  icon: assets/indent-logo.png
  logo: assets/indent-logo.png

nav:
- index.md
- 개발 가이드:
  - coding_style/python.md
  - coding_style/js_ts.md
- 깃 (Git):
  - git/repository.md
  - git/commit.md
  - git/pr.md
- 인프라스트럭쳐:
  - infrastructure/aws.md
  - infrastructure/terraform.md
- 기여:
  - contribution/contribution.md


markdown_extensions:
- toc:
    permalink: True
- pymdownx.highlight
- pymdownx.superfences
- attr_list
- pymdownx.tabbed:
    alternate_style: true

