site_name: Style Guide For Indenters
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: blue grey

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  # icon:
  logo: assets/indent-logo.png

nav:
- index.md
- Coding Style:
  - coding_style/python.md
  - coding_style/js_ts.md
- Git:
  - git/repository.md
  - git/commit.md
- Infrastructure:
  - infrastructure/aws.md
  - infrastructure/terraform.md


markdown_extensions:
- toc:
    permalink: True
- pymdownx.highlight
- pymdownx.superfences
- attr_list
